# Generated by Django 6.0.6 on 2026-06-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_task_tasks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
